[package]
name = "sage_broker"
version = "0.1.0"
description = "MQTT 5.0 broker"
authors = ["Kevin D'ORANGE <kevin.dorange@gmail.com>"]
edition = "2018"
repository = "https://github.com/OragonEfreet/broker"
readme = "README.md"
license = "MIT"
keywords = ["mqtt", "broker", "iot"]
categories = ["command-line-utilities", "network-programming", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sage_mqtt = { git = "https://github.com/OragonEfreet/sage_mqtt", branch = "dev" }
async-std = "1.6.0"
log = "0.4.8"
pretty_env_logger = "0.4.0"
