[package]
name = "sage_broker"
version = "0.1.0"
authors = ["Kevin D'ORANGE <kevin.dorange@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
